import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  datasetStats: defineTable({ key: v.string(), value: v.optional(v.number()), translations: v.optional(v.number()), verses: v.optional(v.number()), books: v.optional(v.number()), crossReferences: v.optional(v.number()), entities: v.optional(v.number()), lexiconEntries: v.optional(v.number()) }).index("by_key", ["key"]),
  translations: defineTable({ id: v.string(), name: v.string(), language: v.string(), license: v.string(), sourceUrl: v.optional(v.string()), verseCount: v.number(), description: v.optional(v.string()), licenseUrl: v.optional(v.string()) }).index("by_identifier", ["id"]),
  books: defineTable({ translation: v.string(), id: v.string(), name: v.string(), chapters: v.number(), order: v.number() }).index("by_translation", ["translation"]),
  verses: defineTable({ translation: v.string(), book: v.string(), chapter: v.number(), verse: v.number(), reference: v.string(), text: v.string(), sortOrder: v.number() }).index("by_translation", ["translation"]).index("by_chapter", ["translation", "book", "chapter"]).index("by_reference", ["translation", "reference"]).searchIndex("search_text", { searchField: "text", filterFields: ["translation"] }),
  passages: defineTable({ id: v.optional(v.string()), translation: v.string(), ref: v.string(), title: v.string(), book: v.string(), chapter: v.number(), verse: v.number(), endVerse: v.number(), text: v.string(), context: v.optional(v.string()), speaker: v.optional(v.string()), audience: v.optional(v.string()), genre: v.optional(v.string()), tags: v.optional(v.array(v.string())), themes: v.optional(v.array(v.string())), entities: v.optional(v.array(v.string())), searchText: v.string(), cautions: v.optional(v.array(v.string())), provenance: v.optional(v.any()) }).index("by_translation", ["translation"]).index("by_ref", ["translation", "ref"]).searchIndex("search_text", { searchField: "searchText", filterFields: ["translation"] }),
  crossReferences: defineTable({ from: v.string(), to: v.string(), label: v.string(), type: v.optional(v.string()), weight: v.number() }).index("by_from", ["from"]).index("by_to", ["to"]),
  lexicon: defineTable({ id: v.string(), strong: v.string(), lemma: v.string(), transliteration: v.string(), language: v.string(), morphology: v.string(), gloss: v.string(), definition: v.optional(v.string()), source: v.string(), license: v.string() }).index("by_strong", ["strong"]).searchIndex("search_gloss", { searchField: "gloss", filterFields: ["language"] }),
  entities: defineTable({ id: v.string(), name: v.string(), type: v.string(), description: v.optional(v.string()), aliases: v.optional(v.array(v.string())), refs: v.array(v.string()) }).index("by_identifier", ["id"]).searchIndex("search_name", { searchField: "name", filterFields: ["type"] }),
  expansions: defineTable({ passageRef: v.string(), translation: v.string(), type: v.string(), text: v.string(), status: v.union(v.literal("draft"), v.literal("approved"), v.literal("rejected")), source: v.optional(v.string()), confidence: v.optional(v.number()), tags: v.optional(v.array(v.string())), createdAt: v.optional(v.number()), model: v.optional(v.string()), version: v.optional(v.string()), sourceText: v.optional(v.string()), faithfulness: v.optional(v.any()), provenance: v.optional(v.any()) }).index("by_ref", ["passageRef"]).index("by_status", ["status"]).searchIndex("search_text", { searchField: "text", filterFields: ["translation", "status"] }),
  savedPassages: defineTable({ sessionId: v.string(), ref: v.string(), translation: v.string(), note: v.string(), title: v.optional(v.string()), text: v.optional(v.string()), createdAt: v.number() }).index("by_session", ["sessionId"]).index("by_session_ref", ["sessionId", "translation", "ref"]),
  evaluationRuns: defineTable({ createdAt: v.number(), status: v.string(), total: v.number(), passed: v.number(), score: v.number(), results: v.array(v.any()), durationMs: v.number(), baselineScore: v.optional(v.number()), metadata: v.optional(v.any()) }),
  jobs: defineTable({ kind: v.string(), status: v.string(), total: v.number(), processed: v.number(), createdAt: v.number(), updatedAt: v.optional(v.number()), error: v.optional(v.string()), metadata: v.optional(v.any()) }).index("by_kind", ["kind"]),
});
