#!/usr/bin/env node
/** Package the built Vite app into a Convex HTTP module; no external host required. */
import {readdir,readFile,writeFile,mkdir,access} from 'node:fs/promises';
import {resolve,join,extname,relative,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const dist=join(root,'dist');
if(process.argv.includes('--ensure') || process.argv.includes('--initialize')) {
  const output=join(root,'convex/siteAssets.ts');
  try {await access(output);} catch {
    await mkdir(join(root,'convex'),{recursive:true});
    await writeFile(output,'// Initialized before build; scripts/build-hosting.mjs replaces this with dist assets.\nexport type SiteAsset={body:string;contentType:string;base64:boolean;immutable:boolean};\nexport const siteAssets:Record<string,SiteAsset>={};\n');
  }
  process.exit(0);
}
const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json; charset=utf-8','.txt':'text/plain; charset=utf-8','.xml':'application/xml; charset=utf-8','.ico':'image/x-icon','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.woff':'font/woff','.woff2':'font/woff2'};
const textExtensions=new Set(['.html','.js','.css','.svg','.json','.txt','.xml']);
const assets={};let bytes=0;
async function walk(dir){
 for(const entry of await readdir(dir,{withFileTypes:true})){
  const path=join(dir,entry.name);
  if(entry.isDirectory()){await walk(path);continue;}
  if(!entry.isFile() || entry.name.endsWith('.map'))continue;
  const data=await readFile(path),extension=extname(path).toLowerCase();
  const pathname='/'+relative(dist,path).split(sep).join('/');
  bytes+=data.length;
  assets[pathname]={body:data.toString(textExtensions.has(extension)?'utf8':'base64'),contentType:types[extension] || 'application/octet-stream',base64:!textExtensions.has(extension),immutable:pathname.startsWith('/assets/')};
 }
}
await walk(dist);
if(!assets['/index.html'])throw new Error('dist/index.html is missing; run npm run build first.');
if(bytes>12*1024*1024)throw new Error('Static bundle exceeds this lightweight Convex hosting adapter\'s 12 MiB cap.');
await mkdir(join(root,'convex'),{recursive:true});
await writeFile(join(root,'convex/siteAssets.ts'),`// Generated by scripts/build-hosting.mjs; do not edit.\nexport type SiteAsset = {body:string;contentType:string;base64:boolean;immutable:boolean};\nexport const siteAssets: Record<string,SiteAsset> = ${JSON.stringify(assets)};\n`);
console.log(`Packaged ${Object.keys(assets).length} static assets (${bytes.toLocaleString()} bytes) for the Convex .site URL.`);
